name: Build and deploy Node.js app to Azure Web App - InternalReporting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Run all shell steps in the app subfolder
    defaults:
      run:
        working-directory: KK_Icons

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          npm ci
          npm run build
        # Optional: if you want manifest URLs baked in at build-time:
        # env:
        #   APP_BASE_URL: https://<yourapp>.azurewebsites.net/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # Upload the KK_Icons app folder (contains package.json, server.js, dist/)
          path: KK_Icons

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1AE7E1FCD9FC4178BF26C77087006F82 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_707994B3FB4346349673FCA5AFC7D7C3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2B3E5957F25F475DAF1FFC03955B2465 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'InternalReporting'
          slot-name: 'Production'
          # Deploy the app subfolder that contains package.json/server.js/dist
          package: KK_Icons
